# Generated by Django 4.1 on 2022-09-01 23:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listitem',
            name='time',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
